Implement model
Athenais/M2BI-db-project pull request #22
Opened 2017-03-17 00:05 UTC by Athenais

This is the implementation of the old diagram as added in #19.

TODO : relations between tables as explained in : 
http://flask-sqlalchemy.pocoo.org/2.1/models/
once done : will close #9

2017-03-17 00:34 UTC, Athenais commented
@NicolasBourassin : si on implémente le model dont on avait parlé pdt les réunions, c'est sur cette branche. ;)

2017-03-25 11:07 UTC, jecarvaill requested changes

2017-03-25 11:07 UTC, jecarvaill commented on app/model.py
> +    result = db.Column(db.String)
If the type of variable seq is TEXT, so the type of variable result should be the same TEXT.

2017-03-25 11:07 UTC, jecarvaill commented on app/model.py
> +    header = db.Column(db.String)
I think, we should use TEXT instead of String for the header variable.

2017-03-25 13:39 UTC, merged