About
Athenais/M2BI-db-project pull request #42
Opened 2017-04-09 17:33 UTC by NicolasBourassin

2017-04-09 17:41 UTC, CharlottePerin requested changes
"La page about, générée dynamiquement donnera des informations statistiques sur votre base de données (nombre d’acide aminés en structure Polyproline disponibles, nombre de protéines, nombre de requêtes réalisées, par exemple)."

2017-04-10 21:07 UTC, Athenais commented
- [X] Nombre de fichier pdb dans la db =  nombre de protéines ? : fait par @jecarvaill 


- [ ] Nombre d’acide aminés en structure Polyproline disponibles : 
occurence de la lettre 'P' dans les annotations. 

le code devrait ressembler à ça : 
```
for all annotation in model.Annotations.query.all() : 
    annotation.result.count('P')
```
je vais le tester ce soir 


- [ ] mais du coup, une autre que vous pouvez essayer de faire, c'est le nombre de P par type d'annotation. Tips : au lieu de faire ` model.Annotations.query.all() ` il faut utiliser la fonction filter, si je ne m'abuse. 

- [ ] nombre de requêtes réalisées, par exemple
Aucune idée à part stocker ca dans un fichier. En plus nombre de requete de quoi , arg. :/ (c'pour ca que je vous en propose une autre. ^_^

2017-04-11 17:10 UTC, nanls requested changes

2017-04-11 17:10 UTC, Athenais commented on app/views.py
> +    mean_resol = 0
http://stackoverflow.com/questions/7143235/how-to-use-avg-and-sum-in-sqlalchemy-query

2017-04-11 17:17 UTC, Athenais commented on app/views.py
> +    mean_resol = 0
Inspire toi de la 2e reponse : http://stackoverflow.com/a/17435020

2017-04-11 18:25 UTC, nanls approved these changes

2017-04-11 19:09 UTC, CharlottePerin requested changes
dans ramachandran.py:
lignes 145-147:
alors, le dossier, c'était temp et c'était comme ça partout donc il faut arrêter de mettre dans tmp comme ça d'un coup
et moi, ce que je veux, c'est un truc du type temp/4DMI.png

Dans views.py, ligne 5:
pourquoi avoir retiré le import Annotation? il est utilisé dans insert()

2017-04-11 19:39 UTC, CharlottePerin approved these changes

2017-04-11 19:41 UTC, merged