Save data in db
Athenais/M2BI-db-project pull request #45
Opened 2017-04-10 20:02 UTC by Athenais

2017-04-11 19:24 UTC, CharlottePerin requested changes
Dans views: faire en sorte de vérifier que le pdb n'est pas déjà dans la base avant de tout calculer

2017-04-12 08:13 UTC, CharlottePerin reviewed
Euh... les changements de save data in db sont donc la mise en place de la page about?

2017-04-12 09:13 UTC, Athenais commented
whut ?

2017-04-12 09:18 UTC, Athenais commented on app/views.py
> +        pdb_id = filename[0:4]
A ce moment là, on a l'id, on essaye de get un pdb par la primary key (`query.get(PK)`) Si c'est `None`, on fait la suite, sinon, on print que c'était déjà dans la dbb. 
Qqn veut essayer ? @CharlottePerin  @jecarvaill  @NicolasBourassin ?

2017-04-12 09:36 UTC, CharlottePerin commented on app/views.py
> +        pdb_id = filename[0:4]
pourquoi c'est dans l'index et pas dans upload?

2017-04-12 09:41 UTC, jecarvaill commented
Si c'est dans upload ?

2017-04-12 11:36 GMT+02:00 CharlottePerin <notifications@github.com>:

> *@CharlottePerin* commented on this pull request.
> ------------------------------
>
> In app/views.py
> <https://github.com/Athenais/M2BI-db-project/pull/45#discussion_r111105151>
> :
>
> > @@ -29,13 +31,28 @@ def upload():
>              storage = form.pdb_file.data, # The uploaded file to save
>          )
>          print (filename)
> +
> +        pdb_id = filename[0:4]
>
> pourquoi c'est dans l'index et pas dans upload?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Athenais/M2BI-db-project/pull/45#discussion_r111105151>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYsi5Fckw9-iXQ6tzZwHiehGH8df3ABRks5rvJs1gaJpZM4M5QJ2>
> .
>

2017-04-12 09:45 UTC, Athenais commented on app/views.py
> +        pdb_id = filename[0:4]
heu. C'est dans upload. ^_^
![capture du 2017-04-12 11-45-21](https://cloud.githubusercontent.com/assets/3973705/24951673/800c5c80-1f75-11e7-8c8a-d092b9992f82.png)

2017-04-12 10:58 UTC, jecarvaill commented
La vérification fonctionne, cependant un problème apparait au niveau du model de la db 

OperationalError: (sqlite3.OperationalError) table pdb_file has no column named keywords [SQL: u'INSERT INTO pdb_file (id, seq, keywords, name, head, deposition_date, release_date, structure_method, resolution, structure_reference, journal_reference, author, compound) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('xy_7', 'KVFGRCELAAAMKRHGLNNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL', 'hydrolase, glycosidase, electrostatic interaction, helix, hen lysozyme, stability', ' analysis of the stabilization of hen lysozyme with the helix dipole and charged side chains', 'hydrolase', '1996-11-22', '1997-11-26', 'x-ray diffraction', 1.79, '[]', 'h.motoshima,s.mine,k.masumoto,y.abe,h.iwashita, y.hashimoto,y.chijiiwa,t.ueda,t.imoto analysis of the stabilization of hen lysozyme by helix macrodipole and charged side chain interaction. j.biochem.(tokyo) v. 121 1076 1997 issn 0021-924x 9354379 ', 'H.Motoshima,T.Ohmura,T.Ueda,T.Imoto', "{'1': {'chain': 'a', 'misc': '', 'molecule': 'lysozyme', 'ec_number': '3.2.1.17', 'engineered': 'yes', 'ec': '3.2.1.17', 'mutation': 'yes'}}")]

2017-04-12 11:18 UTC, jecarvaill commented
NB:
Il serait aussi astucieux de ne stocker le fichier pdb uniquement dans le cas où le fichier n'existe pas.
filename = pdb_set.save(storage = form.pdb_file.data,)) # The uploaded file to save

2017-04-12 12:08 UTC, CharlottePerin commented
ben c'est ce que je demandais de faire

2017-04-12 12:18 UTC, Athenais commented on app/views.py
>          check_pdb = db.session.query(model.PDBFile).filter(model.PDBFile.id==pdb_id)
pour recupererr un element par la primary key, il faut utiliser get.

2017-04-12 12:19 UTC, Athenais commented on app/views.py
> +        check_bool = db.session.query(check_pdb.exists()).scalar()
et du coup je comprends pas l'interet de cette ligne. 

une fois que t'as recup le pdb par la PK, tu regardes si c'est none ou pas.

2017-04-12 12:20 UTC, nanls commented on app/views.py
> +        if not check_bool:
tu coup : if not pdb_file :

2017-04-12 12:24 UTC, Athenais commented on app/views.py
> +        check_pdb = db.session.query(model.PDBFile).filter(model.PDBFile.id==form.pdb_file.data.filename[0:4])
uis pq tu te sers pas de pdb_id directement ?

2017-04-12 12:25 UTC, jecarvaill commented on app/views.py
>          check_pdb = db.session.query(model.PDBFile).filter(model.PDBFile.id==pdb_id)
La méthode fonctionne, tu souhaites la changer ?

2017-04-12 12:25 UTC, jecarvaill commented on app/views.py
> +        check_pdb = db.session.query(model.PDBFile).filter(model.PDBFile.id==form.pdb_file.data.filename[0:4])
parce qu'il n'est pas encore connu, vu qu'il n'y a pas eu d'insertion.

2017-04-12 12:30 UTC, Athenais commented on app/views.py
>          check_pdb = db.session.query(model.PDBFile).filter(model.PDBFile.id==pdb_id)
ben c'est syntaxiquement incorrect, quoi. puis ça me donne l'impression que vous lisez pas quand je vous donne les tuyaux. 
![capture du 2017-04-12 14-30-10](https://cloud.githubusercontent.com/assets/3973705/24957620/96cdc50a-1f8c-11e7-8541-f01f8a1c8874.png)

2017-04-12 12:33 UTC, Athenais commented on app/views.py
> +        check_pdb = db.session.query(model.PDBFile).filter(model.PDBFile.id==form.pdb_file.data.filename[0:4])
my bad, j'avais pas vu la suppression de l'upload.

2017-04-12 12:38 UTC, Athenais commented
@jecarvaill , quand t'as fini, tu check la box tout en haut en on passe à la review ?

2017-04-12 12:40 UTC, jecarvaill commented
j'ai besoin de ton scipt de génération de la bdd, j'ai pas la bonne version
générée.

2017-04-12 14:38 GMT+02:00 Athénaïs Vaginay <notifications@github.com>:

> @jecarvaill <https://github.com/jecarvaill> , quand t'as fini, tu check
> la box tout en haut en on passe à la review ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Athenais/M2BI-db-project/pull/45#issuecomment-293563122>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYsi5Ib57rb3_F8OLN73XLRvqLguDNaaks5rvMXZgaJpZM4M5QJ2>
> .
>

2017-04-12 13:08 UTC, jecarvaill commented
Review possible

2017-04-12 13:34 UTC, NicolasBourassin approved these changes
ça me paraît correct, les rares trucs que j'ai vu d'incorrect sont de l'ordre du nettoyage de codes (commentaires pas à jour, print() obsolètes etc.) donc ça attendra

2017-04-12 15:01 UTC, Athenais commented on app/views.py
> -        print (filesForm.resMin.data)
De manière général, merci de me laisser mes prints de débogage tant qu'on a pas fini le sujet minimal. Je vous jure que je m'en sers...

2017-04-12 15:30 UTC, NicolasBourassin commented on app/views.py
> -        print (filesForm.resMin.data)
Rappel d'un message précédent : "les rares trucs que j'ai vu d'incorrect sont de l'ordre du nettoyage de codes (commentaires pas à jour, print() obsolètes etc.) donc **ça attendra**."

Comme dit Athé, les print() de debug peuvent encore servir, on les retirera quand on arrêtera de toucher au reste du code.

2017-04-15 18:57 UTC, Athenais commented
@CharlottePerin  : je force le merge.

2017-04-15 19:02 UTC, merged