Result page
Athenais/M2BI-db-project pull request #52
Opened 2017-04-11 20:45 UTC by CharlottePerin

Ajout du template pour la page de résultats détaillés et les fonctions associées dans views.py

2017-04-11 20:55 UTC, CharlottePerin commented
Il faudrait virer printNumbers&Sequence.py mais je vois pas comment faire alors bon, c'est dommage

2017-04-11 23:46 UTC, nanls requested changes
Je me rends compte que 'st tout fouilli, alors en bref, voilà la fonction qui prend en compte toutes mes remarques : 


```
def positionsPrinter(length):
    """
    Create a string containing the position numbers in a way that they will be
    aligned with the sequence.
    ARGUMENT:
        length of the sequence to consider.
    """
    numbers = range(10, length + 1, 10)
    pos =""
    for number in numbers:
        pos += "{:>10d}".format(number )
    return pos + "\n"

```

2017-04-11 23:46 UTC, Athenais commented on app/views.py
> +    numbers = range(0, 10000, 10)
Oulà, ca sent la fatigue : ya 2-3 trucs qui collent pas. XD 

- en Python 3, ya pas mal de truc sur lequel ca clash

- pourquoi générer une liste grande, alors qu etu connais la longueur ?

2017-04-11 23:46 UTC, Athenais commented on app/views.py
> +    numbers[0] = 1
en python 3, un range ne donne pas une liste mais un range, qui est immuable, donc tu peux pas changer la valeur apres coup. 

Donc à la rigueur, je te propose un : 
` numbers = [1].extend(  range(10, length, 10) ) `
et du coup ca fait une liste et pas un range.

2017-04-11 23:46 UTC, Athenais commented on app/views.py
> +            pos += "{:<9d}".format(numbers[0])
faire un if alors que tu sais qu'il va s'effectuer que la premiere fois, c'est dommage, je te propose un 

`pos = "{:<9d}".format(numbers[0])` (ou meme directement : `pos = 1`) 
puis de commencer la boucle en concaténant la suite.

2017-04-11 23:46 UTC, Athenais commented on app/views.py
> +    for i in xrange((length/10)+1):
en Python 3 : les xrange ,n'existent pas, les ranges font le boulot.

2017-04-11 23:46 UTC, Athenais commented on app/views.py
> +    for i in xrange((length/10)+1):
et aussi, en utilisant lenght pour générer numbers, ya pas besoin de ce range là, du coup. \o/ :D

2017-04-11 23:46 UTC, Athenais commented on app/views.py
> +            pos += "{:<10d}".format(numbers[i])
en Python 3, je crois qu'on peut pas acceder à un element comment ca. 
Mais du coup, en utilisant number dans le for, ya pas besoin de l'indexation.

2017-04-11 23:46 UTC, Athenais commented on app/views.py
> +            pos += "{:<10d}".format(numbers[i])
En fait, en ne mettant pas de 1 et en alignat à droite plutot qu'à gauche, on peut même supprimer qq lignes de code. (genre tout ce qui concerne le premier élément).

2017-04-12 00:20 UTC, Athenais commented on app/views.py
> +        annot["{<:7s}".format(annotations["method"])] = annotations["result"]
je suis pas sure de comprendre ce que tu voulais faire. Mais là je sers plus à rien, alors je pose ça là, et go dodo ! \o/ :D

2017-04-12 07:47 UTC, CharlottePerin commented
J'ai pas vraiment compris tes remarques là
enfin en gros, il y avait un comm au dessus de if esle avant qui disait "je sais pas pourquoi, mais c'est comme ça qu'il veut sinon, ça ne marche pas"
et concernant ce code, c'était bien "{:<}" et non pas "{:>}"

2017-04-12 08:44 UTC, Athenais commented
haha, j'avoue que c'était plus très clair. XD

2017-04-12 08:53 UTC, CharlottePerin commented
Du coup, le code est bon non?

2017-04-12 09:10 UTC, Athenais commented
Ben celui qu'il y avait marchait pas (pour toute les raisons liées à Python 2 / 3). Mais maintenant, oui. Hésitez pas à tester, d'ailleurs.

2017-04-12 09:49 UTC, CharlottePerin commented
Le code marche complètement mainteannt (tu commençais les positions à 10 plutôt que 1)

2017-04-12 10:07 UTC, CharlottePerin commented on app/views.py
> +        annot["{<:7s}".format(annotations["method"])] = annotations["result"]
ah! alors:
je récupère toutes les annotations disponibles pour un pdb
puis
je crée un dictionnaire construit tel que, par example:
{"DSSP   ": "rkeqbgkerglergkrkkkkr"}
donc nom de la méthode sur 7 caractères (pour l'affichage): annotation
ce dictionnaire sera ensuite parcouru et affiché dans le template associé

2017-04-12 10:08 UTC, CharlottePerin commented on app/views.py
> +        annot["{<:7s}".format(annotations["method"])] = annotations["result"]
et il a pas aimé mais j'ai vraiment écrit: "DSSP" avec 3 espaces ensuite

2017-04-12 10:24 UTC, Athenais commented
ouais, je m’étais qu'on s'en foutait du 1. Mais merci d'avoir pris le temps de corriger. :)

2017-04-12 10:24 UTC, Athenais commented on app/views.py
> +    pos = "{:<9d}".format(1)
Merci, @CharlottePerin . :)

2017-04-12 10:34 UTC, Athenais commented on app/views.py
> +        annot["{<:7s}".format(annotations["method"])] = annotations["result"]
okokok

2017-04-12 12:36 UTC, nanls approved these changes

2017-04-12 13:31 UTC, merged

2017-04-12 13:32 UTC, Athenais commented
bouhouhou, c'était pas fini, @jecarvaill :'(

2017-04-12 13:40 UTC, jecarvaill commented
Je ne savais pas, j'ai vu qu'il fallait merge. Je pensais bien faire 😫

2017-04-12 15:32 GMT+02:00 Athénaïs Vaginay <notifications@github.com>:

> bouhouhou, c'était pas fini, @jecarvaill <https://github.com/jecarvaill>
> :'(
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Athenais/M2BI-db-project/pull/52#issuecomment-293577079>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYsi5F56PqT4M9-uMPqhq3o8XhB4H_nIks5rvNJ8gaJpZM4M6oFa>
> .
>