creation of a ramachandran map WIP
Athenais/M2BI-db-project pull request #63
Opened 2017-04-16 19:51 UTC by jecarvaill

2017-04-16 20:02 UTC, jecarvaill commented
Toutes les cartes  sont générées, reste à traiter les couleur des points en fonction des annotations.

2017-04-16 21:29 UTC, Athenais commented
@jecarvaill : des que c'est bon, bip moi pour les modif sur la vue, du coup. ;)

2017-04-16 21:41 UTC, jecarvaill commented
Review possible

2017-04-16 22:35 UTC, nanls requested changes

2017-04-16 22:35 UTC, Athenais commented on app/ramachandran.py
> +    for method in methods:
great. :)

2017-04-16 22:35 UTC, Athenais commented on app/ramachandran.py
> +
Alors la logique SQLALchemy : 
on a des objets, servons nous en. 
```
get le pdb par l'id (fonction get). 
pdb.annotations.all() # renvoit un tableau d'object annotation. 

pour chaque annotation dans ce tableau : 
    annotation.method # te file la méthode
    annotation.result # te file l'annotation lié à cette annotation. 
```

Vu l'heure, j'ai un peu peu de bidouiller ton code s'il marche, mais bon, c'etait pour te montrer la logique.

2017-04-16 22:35 UTC, Athenais commented on app/ramachandran.py
> +        angles = db.session.query(model.Angle).filter(model.Angle.pdb_id==pdb_id)
idem, si t'as récupéré le pdb grace à get, tu peut faire pdb.angles.all()

2017-04-16 22:35 UTC, Athenais commented on app/ramachandran.py
> +        psi = [angles[i].psi for i in range(1,len(angles.all())-1)]
perso j'avais utilisé un truc du genre  :
```
 angles_phi, angles_psi = zip(*[ (angle.phi, angle.psi) for angle in pdb.angles.all()])
```
C'est plus concis (et plus clair (enfin je trouve. XD) ) 

meme si tu veux vriament faire en 2 étapes, pourquoi pas un truc du genre : 
```
[angle.phi for angle in angles]
```
pourquoi paser par une indiciation ? 

si la réponse est : 
> écoute, meuf, il est dimanche minuit, alors taggle

je comprendrais. :p

2017-04-16 22:35 UTC, Athenais commented on app/ramachandran.py
> +            df = pd.DataFrame(dict(phi=phi, psi=psi, color=annotation))
panda ? :D oh, j'ai jamais uilisé. Great ! :D

2017-04-16 22:35 UTC, Athenais commented on app/views.py
> +    annot = {}
hii, mais pourquoi c'est là, ca ? j'avais tout viré. :/

2017-04-16 22:35 UTC, Athenais commented on app/views.py
> +    annot = {}
arf, c'est ptt pdb t'as résolution de conflict. :/

2017-04-16 23:17 UTC, Athenais commented
T'es sur qe ca marche chez toi ? 
j'ai un 

  File "/home/nanis/Documents/M2BI/projet-bdd/app/ramachandran.py", line 73, in compute_ramachandran_map
    annotation = db.session.query(model.Annotation.result).filter(and_(model.Annotation.pdb_id==pdb_id,
 "Object %r is not legal as a SQL literal value" % value)
sqlalchemy.exc.ArgumentError: Object <model.PDBFile object at 0x7fe760cdedd8> is not legal as a SQL literal value

:/

2017-04-16 23:25 UTC, Athenais commented
bon, du coup, meme si j'arrive pas a tester, j'ai fait le truc sur le template.

2017-04-16 23:25 UTC, Athenais commented
Si tu m'assure que ca marche chez toi, j'essayerai de creuser un peu plus. ^^

2017-04-17 01:22 UTC, Athenais commented
je viens de fixer un putain de conflict, j'espere qu eje n'ai pas tout cassé, haha.

2017-04-17 06:16 UTC, jecarvaill commented on app/ramachandran.py
> +
le list me sert juste à transformer la string annotation en une liste de char, pas compris la question.

2017-04-17 06:23 UTC, jecarvaill commented on app/ramachandran.py
> +        psi = [angles[i].psi for i in range(1,len(angles.all())-1)]
parce qu'il faut ignorer le premier er dernier angle phi ou psi.

2017-04-17 06:23 UTC, jecarvaill commented
Tester ce matin. Fonctionne bien de mon côté.

2017-04-17 06:25 UTC, jecarvaill commented
Tester ce matin, fonctionne bien. \o/

2017-04-17 08:05 UTC, jecarvaill commented
J'ai pas réussi à adapter le template pour resultsForOnePDB. Ca doit être trivial mais je ne vois pas.

2017-04-17 10:14 UTC, Athenais commented
@jecarvaill : je l'ai fait hier 040cf15

2017-04-17 10:17 UTC, Athenais commented
@jecarvaill : je merge en te faisant confiance. :p

2017-04-17 10:17 UTC, merged

2017-04-17 10:17 UTC, jecarvaill commented
Oui c'est bien ça, mais je ne voyais pas de graphique =S